<?php
namespace App\Filament\Resources\OrderRequests;
use App\Filament\Resources\OrderRequests\Pages\{EditOrderRequest,ListOrderRequests}; use App\Models\OrderRequest; use BackedEnum; use Filament\Resources\Resource; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\Table; use Filament\Forms\Components\{Repeater,Select,TextInput,Textarea}; use Filament\Tables\Columns\TextColumn;
class OrderRequestResource extends Resource {
 protected static ?string $model=OrderRequest::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedShoppingBag; protected static ?string $navigationLabel='Pedidos de Encomenda'; protected static ?string $modelLabel='pedido de encomenda'; protected static ?string $pluralModelLabel='pedidos de encomenda'; protected static string|\UnitEnum|null $navigationGroup='Comercial';
 public static function form(Schema $schema):Schema{return $schema->components([TextInput::make('reference')->disabled(),Select::make('status')->options(['new'=>'Novo','reviewing'=>'Em análise','proposal_sent'=>'Proposta enviada','confirmed'=>'Confirmado','unavailable'=>'Sem disponibilidade','closed'=>'Fechado'])->required(),Select::make('customer_type')->options(['private'=>'Particular','professional'=>'Instalador / Profissional','reseller'=>'Revendedor'])->disabled(),TextInput::make('name')->disabled(),TextInput::make('email')->disabled(),TextInput::make('phone')->disabled(),TextInput::make('region')->disabled(),Textarea::make('notes')->disabled()->columnSpanFull(),Repeater::make('items')->relationship()->schema([TextInput::make('quantity')->disabled(),TextInput::make('product_name')->disabled(),TextInput::make('variant_name')->disabled()])->columns(3)->columnSpanFull(),Textarea::make('internal_notes')->columnSpanFull()]);}
 public static function table(Table $table):Table{return $table->columns([TextColumn::make('created_at')->label('Recebido')->dateTime('d/m/Y H:i')->sortable(),TextColumn::make('reference')->searchable(),TextColumn::make('name')->searchable(),TextColumn::make('customer_type')->label('Cliente'),TextColumn::make('region'),TextColumn::make('status')->badge()])->recordActions([\Filament\Actions\EditAction::make()]);}
 public static function getPages():array{return ['index'=>ListOrderRequests::route('/'),'edit'=>EditOrderRequest::route('/{record}/edit')];}
}
