@extends('layouts.site')
@section('title','Finalizar compra | TROPIKAL')
@section('content')
<section class="page-hero compact"><div class="container"><span class="eyebrow">{{ $stripeReady ? 'Pagamento seguro' : 'Encomenda sujeita a confirmação' }}</span><h1>{{ $stripeReady ? 'Finalizar compra' : 'Enviar pedido de encomenda' }}</h1><p>{{ $stripeReady ? 'Revise os dados de entrega. O pagamento é processado em segurança pelo Stripe.' : 'Indique os dados de entrega. A Tropikal confirmará preço, disponibilidade, transporte e condições antes de avançar.' }}</p></div></section>
<section class="section"><div class="container checkout-grid">
<div><h2>Resumo</h2>@php($subtotal=0) @foreach($cart as $line)<article class="checkout-line"><strong>{{ $line['quantity'] }} × {{ $line['product']->name }}</strong><span>{{ $line['variant']?->name }} · {{ $line['unit_price']!==null?number_format($line['unit_price']*$line['quantity'],2,',','.').' €':'Sob consulta' }}</span></article>@php($subtotal += ($line['unit_price']??0)*$line['quantity']) @endforeach<hr><p><strong>Subtotal indicativo: {{ number_format($subtotal,2,',','.') }} €</strong></p>@if($stripeReady)<p>Entrega gratuita a partir de 250 €. Abaixo desse valor: 9,90 €.</p><div class="order-disclaimer">Preços com IVA incluído. O pagamento só fica confirmado após validação pelo Stripe.</div>@else<div class="order-disclaimer">O subtotal, os portes, o stock e as condições finais serão confirmados pela Tropikal. Não existe cobrança nesta fase.</div>@endif</div>
<form class="contact-form quote-form" method="post" action="{{ $stripeReady ? route('checkout.pay') : route('checkout.request') }}">@csrf @if($errors->any())<p class="form-feedback is-error">{{ $errors->first() }}</p>@endif
<h2>Contacto e entrega</h2><div class="form-row"><label>Nome<input name="name" value="{{ old('name',$address?->name??auth()->user()->name) }}" required></label><label>Email<input type="email" name="email" value="{{ old('email',auth()->user()->email) }}" required></label></div><div class="form-row"><label>Telefone<input name="phone" value="{{ old('phone',$address?->phone??auth()->user()->phone) }}" required></label><label>NIF<input name="tax_number" value="{{ old('tax_number',$address?->tax_number??auth()->user()->tax_number) }}"></label></div><label>Morada<input name="line1" value="{{ old('line1',$address?->line1) }}" required></label><label>Complemento<input name="line2" value="{{ old('line2',$address?->line2) }}"></label><div class="form-row"><label>Código postal<input name="postal_code" value="{{ old('postal_code',$address?->postal_code) }}" required></label><label>Localidade<input name="city" value="{{ old('city',$address?->city) }}" required></label></div><div class="form-row"><label>Região / ilha<input name="region" value="{{ old('region',$address?->region) }}" required></label><label>País<select name="country_code"><option value="PT">Portugal</option></select></label></div>
<details class="billing-details"><summary>Usar outra morada de faturação</summary><label>Nome / empresa<input name="billing_name" value="{{ old('billing_name') }}"></label><label>Morada<input name="billing_line1" value="{{ old('billing_line1') }}"></label><label>Complemento<input name="billing_line2" value="{{ old('billing_line2') }}"></label><div class="form-row"><label>Código postal<input name="billing_postal_code" value="{{ old('billing_postal_code') }}"></label><label>Localidade<input name="billing_city" value="{{ old('billing_city') }}"></label></div><label>Região<input name="billing_region" value="{{ old('billing_region') }}"></label></details>
@if($stripeReady)<label>Código de desconto<input name="discount_code" value="{{ old('discount_code') }}"></label>@endif<label>Observações<textarea name="notes" rows="3">{{ old('notes') }}</textarea></label><label class="check-label"><input type="checkbox" name="terms" value="1" required><span>{{ $stripeReady ? 'Aceito os termos, a política de privacidade e a obrigação de pagamento.' : 'Compreendo que este pedido está sujeito à confirmação de preço, disponibilidade, transporte e condições pela Tropikal.' }}</span></label><button class="btn btn-primary form-submit" type="submit">{{ $stripeReady ? 'Pagar com Stripe' : 'Enviar pedido para confirmação' }}</button>@unless($stripeReady)<p class="order-disclaimer">Não será efetuada qualquer cobrança. A Tropikal entrará em contacto para confirmar a encomenda.</p>@endunless</form>
</div></section>
@endsection
