@extends('layouts.site')
@section('content')
<section id="home" class="hero hero-home"><div class="hero-overlay"></div><div class="container hero-grid hero-grid-home"><div class="hero-copy reveal"><span class="eyebrow">Energia solar, climatização e automação</span><h1>{{ $settings['hero_title'] ?? 'Energia inteligente para um futuro sustentável' }}</h1><p>{{ $settings['hero_text'] ?? 'Soluções eficientes para casas, empresas, instaladores e revendedores nos Açores.' }}</p><div class="hero-actions"><a class="btn btn-primary" href="{{ route('catalog') }}">Explorar produtos</a><a class="btn btn-secondary" href="#orcamento">Pedir orçamento</a></div><div class="hero-stat-row"><article class="stat-pill"><strong>Técnicos</strong><span>qualificados</span></article><article class="stat-pill"><strong>Venda</strong><span>a instaladores</span></article><article class="stat-pill"><strong>Açores</strong><span>apoio local</span></article></div></div><div class="hero-media reveal reveal-delay"><div class="hero-image-card hero-product-card"><img src="{{ asset('assets/img/products/ar-condicionado-eco.jpg') }}" alt="Ar condicionado Tropikal Série Eco"><span>Produto Tropikal · Série Eco</span></div></div></div></section>

<section id="sobre" class="section about-band"><div class="container about-grid"><div><span class="eyebrow">Tropikal Service Açores</span><h2>Especialistas em conforto, energia e construção</h2><p class="section-intro">Fornecemos equipamentos e mão de obra especializada para particulares, empresas, instaladores e parceiros comerciais.</p></div><div class="about-values"><article><strong>360º</strong><span>Soluções integradas</span></article><article><strong>Local</strong><span>Presença nos Açores</span></article><article><strong>Pro</strong><span>Equipa qualificada</span></article></div></div></section>

<section id="servicos" class="section section-alt solutions-band"><div class="container"><div class="section-heading center"><span class="eyebrow">Soluções completas</span><h2>Encontre a solução certa</h2><p class="section-intro">Tecnologia, eficiência e execução especializada num só parceiro.</p></div><div class="category-grid">@php($categoryImages = ['climatizacao'=>'ar-condicionado-eco.jpg','sistemas-solares'=>'painel-solarspace-700wp.png','domotica'=>'smart-home-paineis.jpg','bombas-de-calor'=>'bomba-xpro300.png'])@foreach($navCategories as $category)<a class="category-card {{ isset($categoryImages[$category->slug]) ? 'category-card-photo' : '' }}" href="{{ route('category',$category) }}">@if(isset($categoryImages[$category->slug]))<img src="{{ asset('assets/img/products/'.$categoryImages[$category->slug]) }}" alt="Produto real: {{ $category->name }}">@endif<div class="category-card-copy"><span class="category-number">0{{ $loop->iteration }}</span><h3>{{ $category->name }}</h3><p>{{ $category->description }}</p><span class="card-link">Ver produtos →</span></div></a>@endforeach</div></div></section>

@if($featured->isNotEmpty())<section class="section featured-band"><div class="container"><div class="section-heading center"><span class="eyebrow">Destaques</span><h2>Produtos Tropikal</h2></div><div class="product-grid">@foreach($featured as $product)@include('partials.product-card')@endforeach</div></div></section>@endif

<section class="section section-contact quote-band" id="orcamento"><div class="container contact-grid"><div class="contact-info"><span class="eyebrow">Fale connosco</span><h2>Peça um orçamento</h2><p>Conte-nos o que procura. O pedido ficará registado e a nossa equipa entrará em contacto.</p><div class="contact-promise"><strong>Resposta personalizada</strong><span>Aconselhamento técnico adaptado ao seu projeto.</span></div></div>@include('partials.quote-form')</div></section>
@endsection
