<?php

use App\Http\Controllers\{AccountController,AuthController,CartController,CheckoutController,QuoteRequestController,SiteController,StripeWebhookController}; use Illuminate\Support\Facades\Route;
Route::get('/',[SiteController::class,'home'])->name('home'); Route::get('/catalogo',[SiteController::class,'catalog'])->name('catalog'); Route::get('/categorias/{category:slug}',[SiteController::class,'category'])->name('category'); Route::get('/produtos/{product:slug}',[SiteController::class,'product'])->name('product'); Route::post('/pedir-orcamento',[QuoteRequestController::class,'store'])->middleware('throttle:5,1')->name('quote.store');
Route::get('/carrinho',[CartController::class,'show'])->name('cart.show'); Route::post('/carrinho/adicionar/{product:slug}',[CartController::class,'add'])->name('cart.add'); Route::patch('/carrinho',[CartController::class,'update'])->name('cart.update');
Route::middleware('guest')->group(function(){Route::get('/entrar',[AuthController::class,'loginForm'])->name('login');Route::post('/entrar',[AuthController::class,'login'])->middleware('throttle:5,1');Route::get('/criar-conta',[AuthController::class,'registerForm'])->name('register');Route::post('/criar-conta',[AuthController::class,'register'])->middleware('throttle:5,1');Route::get('/recuperar-acesso',[AuthController::class,'forgotForm'])->name('password.request');Route::post('/recuperar-acesso',[AuthController::class,'forgot'])->name('password.email')->middleware('throttle:3,1');Route::get('/repor-password/{token}',[AuthController::class,'resetForm'])->name('password.reset');Route::post('/repor-password',[AuthController::class,'reset'])->name('password.update');});
Route::post('/sair',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function(){Route::get('/finalizar-compra',[CheckoutController::class,'show'])->name('checkout.show');Route::post('/finalizar-compra/pagar',[CheckoutController::class,'pay'])->middleware('throttle:5,1')->name('checkout.pay');Route::post('/finalizar-compra/pedir-confirmacao',[CheckoutController::class,'requestConfirmation'])->middleware('throttle:5,1')->name('checkout.request');Route::get('/pedido/recebido/{reference}',[CheckoutController::class,'requestSuccess'])->name('order-request.success');Route::get('/compra/concluida',[CheckoutController::class,'success'])->name('checkout.success');Route::get('/compra/cancelada/{order}',[CheckoutController::class,'cancel'])->name('checkout.cancel');Route::get('/minha-conta',[AccountController::class,'dashboard'])->name('account.dashboard');Route::get('/minha-conta/encomendas',[AccountController::class,'orders'])->name('account.orders');Route::get('/minha-conta/encomendas/{order}',[AccountController::class,'order'])->name('account.order');Route::get('/minha-conta/dados',[AccountController::class,'profile'])->name('account.profile');Route::patch('/minha-conta/dados',[AccountController::class,'updateProfile'])->name('account.profile.update');Route::post('/minha-conta/moradas',[AccountController::class,'address'])->name('account.address');Route::delete('/minha-conta/moradas/{address}',[AccountController::class,'deleteAddress'])->name('account.address.delete');Route::post('/minha-conta/encomendas/{order}/devolucao',[AccountController::class,'return'])->name('account.return');});
Route::post('/stripe/webhook',StripeWebhookController::class)->name('stripe.webhook');
Route::redirect('/paineis-fotovoltaicos.html','/categorias/sistemas-solares',301); Route::redirect('/bombas-de-calor.html','/categorias/bombas-de-calor',301); Route::redirect('/ar-condicionado.html','/categorias/ar-condicionado',301); Route::redirect('/domotica-iot.html','/categorias/domotica',301);
Route::get('/{slug}.html',[SiteController::class,'page'])->name('page');
