<?php
namespace Tests\Feature;
use App\Models\{Category,DiscountCode,OrderRequest,Product,User}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Mail; use Tests\TestCase;
class EcommerceTest extends TestCase { use RefreshDatabase;
 public function test_customer_can_register_and_access_account():void{$this->post('/criar-conta',['name'=>'Cliente','email'=>'cliente@example.com','phone'=>'960000000','customer_type'=>'private','password'=>'palavra-passe-segura','password_confirmation'=>'palavra-passe-segura','terms'=>1])->assertRedirect('/minha-conta');$this->assertAuthenticated();$this->get('/minha-conta')->assertOk()->assertSee('Olá, Cliente');}
 public function test_purchasable_product_can_be_added_and_checkout_requires_login():void{$c=Category::create(['name'=>'Solar','slug'=>'solar']);$p=Product::create(['category_id'=>$c->id,'name'=>'Painel','slug'=>'painel','price'=>100,'is_published'=>true,'is_purchasable'=>true]);$this->post('/carrinho/adicionar/painel',['quantity'=>2])->assertSessionHas('success');$this->get('/carrinho')->assertOk()->assertSee('200,00 €')->assertSee('Entrar para comprar');$this->get('/finalizar-compra')->assertRedirect('/entrar');}
 public function test_stripe_payment_endpoint_is_safely_disabled_without_keys():void{$u=User::factory()->create();$c=Category::create(['name'=>'Solar','slug'=>'solar']);$p=Product::create(['category_id'=>$c->id,'name'=>'Painel','slug'=>'painel','price'=>100,'is_published'=>true,'is_purchasable'=>true]);$this->actingAs($u)->withSession(['order_cart'=>[$p->id.':0'=>['product_id'=>$p->id,'variant_id'=>null,'quantity'=>1]]])->post('/finalizar-compra/pagar')->assertSessionHasErrors('payment');$this->assertDatabaseCount('orders',0);}
 public function test_checkout_creates_confirmation_request_without_stripe():void{Mail::fake();$u=User::factory()->create(['name'=>'Cliente','phone'=>'960000000']);$c=Category::create(['name'=>'Solar','slug'=>'solar']);$p=Product::create(['category_id'=>$c->id,'name'=>'Painel','slug'=>'painel','price'=>100,'is_published'=>true,'is_purchasable'=>true]);$response=$this->actingAs($u)->withSession(['order_cart'=>[$p->id.':0'=>['product_id'=>$p->id,'variant_id'=>null,'quantity'=>2]]])->post('/finalizar-compra/pedir-confirmacao',['name'=>'Cliente','email'=>$u->email,'phone'=>'960000000','line1'=>'Rua Principal 1','postal_code'=>'9500-001','city'=>'Ponta Delgada','region'=>'São Miguel','country_code'=>'PT','terms'=>1]);$response->assertRedirect();$this->assertDatabaseHas('order_requests',['user_id'=>$u->id,'subtotal'=>200,'status'=>'new']);$this->assertDatabaseHas('order_request_items',['product_name'=>'Painel','quantity'=>2]);$this->assertSame([],session('order_cart',[]));}
 public function test_discount_calculation_obeys_limit():void{$d=DiscountCode::create(['code'=>'VERDE10','name'=>'Verde','type'=>'percentage','value'=>10,'minimum_amount'=>50]);$this->assertTrue($d->isValidFor(100));$this->assertSame(10.0,$d->discount(100));}
 public function test_homepage_is_independent_from_catalog_content():void{$this->get('/')->assertOk()->assertSee('Soluções integradas para viver e trabalhar melhor')->assertSee('Açores + Madeira');}
}
