<?php
namespace App\Http\Controllers;
use App\Models\{Address,Order,ReturnRequest}; use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash; use Illuminate\Support\Str;
class AccountController extends Controller {
 public function dashboard(Request $r){return view('account.dashboard',['orders'=>$r->user()->orders()->latest()->limit(5)->get()]);}
 public function orders(Request $r){return view('account.orders',['orders'=>$r->user()->orders()->latest()->paginate(12)]);}
 public function order(Request $r,Order $order){abort_unless($order->user_id===$r->user()->id,404);return view('account.order',['order'=>$order->load('items','returns')]);}
 public function profile(Request $r){return view('account.profile',['addresses'=>$r->user()->addresses]);}
 public function updateProfile(Request $r){$d=$r->validate(['name'=>'required|string|max:120','phone'=>'required|string|max:40','company'=>'nullable|string|max:160','tax_number'=>'nullable|string|max:32','customer_type'=>'required|in:private,professional,reseller','password'=>'nullable|string|min:10|confirmed']);if(empty($d['password']))unset($d['password']);$r->user()->update($d);return back()->with('success','Dados atualizados.');}
 public function address(Request $r){$d=$r->validate(['label'=>'required|string|max:50','name'=>'required|string|max:120','company'=>'nullable|string|max:160','tax_number'=>'nullable|string|max:32','phone'=>'required|string|max:40','line1'=>'required|string|max:180','line2'=>'nullable|string|max:180','postal_code'=>'required|string|max:20','city'=>'required|string|max:100','region'=>'nullable|string|max:100','country_code'=>'required|in:PT','is_default_shipping'=>'nullable|boolean','is_default_billing'=>'nullable|boolean']);$r->user()->addresses()->create($d);return back()->with('success','Morada adicionada.');}
 public function deleteAddress(Request $r,Address $address){abort_unless($address->user_id===$r->user()->id,404);$address->delete();return back()->with('success','Morada removida.');}
 public function return(Request $r,Order $order){abort_unless($order->user_id===$r->user()->id&&$order->payment_status==='paid',404);$d=$r->validate(['reason'=>'required|in:changed_mind,damaged,wrong_item,defective,other','details'=>'nullable|string|max:2000','items'=>'required|array','items.*'=>'integer|min:0']);$return=ReturnRequest::create(['reference'=>'DEV-'.now()->format('ymd').'-'.strtoupper(Str::random(5)),'order_id'=>$order->id,'user_id'=>$r->user()->id,'reason'=>$d['reason'],'details'=>$d['details']??null]);foreach($d['items'] as $id=>$qty){$item=$order->items()->find($id);if($item&&$qty>0&&$qty<=$item->quantity)$return->items()->create(['order_item_id'=>$item->id,'quantity'=>$qty]);}if(!$return->items()->exists()){$return->delete();return back()->withErrors(['items'=>'Selecione pelo menos um artigo.']);}return back()->with('success','Pedido de devolução registado: '.$return->reference);}
}
