<?php
namespace App\Http\Controllers;
use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,Hash,Password}; use Illuminate\Auth\Events\PasswordReset; use Illuminate\Support\Str;
class AuthController extends Controller {
 public function loginForm(){return view('auth.login');} public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|string','remember'=>'nullable|boolean']);if(!Auth::attempt(['email'=>$d['email'],'password'=>$d['password']],(bool)($d['remember']??false)))return back()->withErrors(['email'=>'Email ou palavra-passe incorretos.'])->onlyInput('email');$r->session()->regenerate();return redirect()->intended(route('account.dashboard'));}
 public function registerForm(){return view('auth.register');} public function register(Request $r){$d=$r->validate(['name'=>'required|string|max:120','email'=>'required|email|max:160|unique:users','phone'=>'required|string|max:40','customer_type'=>'required|in:private,professional,reseller','company'=>'nullable|string|max:160','tax_number'=>'nullable|string|max:32','password'=>'required|string|min:10|confirmed','terms'=>'accepted']);$user=User::create($d);Auth::login($user);$r->session()->regenerate();return redirect()->route('account.dashboard');}
 public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect()->route('home');}
 public function forgotForm(){return view('auth.forgot');} public function forgot(Request $r){$r->validate(['email'=>'required|email']);$status=Password::sendResetLink($r->only('email'));return $status===Password::RESET_LINK_SENT?back()->with('status',__($status)):back()->withErrors(['email'=>__($status)]);}
 public function resetForm(Request $r,string $token){return view('auth.reset',['token'=>$token,'email'=>$r->email]);} public function reset(Request $r){$d=$r->validate(['token'=>'required','email'=>'required|email','password'=>'required|min:10|confirmed']);$status=Password::reset($d,function($u,$p){$u->forceFill(['password'=>Hash::make($p),'remember_token'=>Str::random(60)])->save();event(new PasswordReset($u));});return $status===Password::PASSWORD_RESET?redirect()->route('login')->with('status',__($status)):back()->withErrors(['email'=>__($status)]);}
}
