<?php
namespace App\Http\Controllers;
use App\Mail\OrderRequestConfirmation; use App\Models\{DiscountCode,Order,OrderRequest,SiteSetting}; use App\Services\StripeCheckoutService; use Illuminate\Http\Request; use Illuminate\Support\Facades\{DB,Mail}; use Illuminate\Support\Str;
class CheckoutController extends Controller {
 public function show(Request $r,CartController $cart){$lines=$cart->hydrate($r);if($lines->isEmpty())return redirect()->route('cart.show');$address=$r->user()->addresses()->where('is_default_shipping',true)->first()??$r->user()->addresses()->first();return view('checkout',['cart'=>$lines,'address'=>$address,'stripeReady'=>(bool)config('services.stripe.secret')]);}
 public function pay(Request $r,CartController $cart,StripeCheckoutService $stripe){if(!config('services.stripe.secret'))return back()->withErrors(['payment'=>'Os pagamentos ainda não estão configurados.']);$lines=$cart->hydrate($r);abort_if($lines->isEmpty(),422);foreach($lines as $l)if(!$l['purchasable'])return back()->withErrors(['cart'=>$l['product']->name.' está disponível apenas sob consulta.']);$d=$r->validate(['name'=>'required|string|max:120','email'=>'required|email|max:160','phone'=>'required|string|max:40','tax_number'=>'nullable|string|max:32','line1'=>'required|string|max:180','line2'=>'nullable|string|max:180','postal_code'=>'required|string|max:20','city'=>'required|string|max:100','region'=>'required|string|max:100','country_code'=>'required|in:PT','billing_name'=>'nullable|required_with:billing_line1|string|max:120','billing_line1'=>'nullable|string|max:180','billing_line2'=>'nullable|string|max:180','billing_postal_code'=>'nullable|required_with:billing_line1|string|max:20','billing_city'=>'nullable|required_with:billing_line1|string|max:100','billing_region'=>'nullable|string|max:100','notes'=>'nullable|string|max:2000','discount_code'=>'nullable|string|max:50','terms'=>'accepted']);
  $subtotal=round($lines->sum(fn($l)=>$l['unit_price']*$l['quantity']),2);$discount=null;$discountTotal=0;if($d['discount_code']??null){$discount=DiscountCode::whereRaw('UPPER(code)=?',[strtoupper($d['discount_code'])])->first();$used=$discount?$r->user()->orders()->where('discount_code_id',$discount->id)->whereNotIn('status',['cancelled'])->count():0;if(!$discount||!$discount->isValidFor($subtotal)||$used>=$discount->per_customer_limit)return back()->withErrors(['discount_code'=>'O código de desconto não é válido.'])->withInput();$discountTotal=$discount->discount($subtotal);}
  $shipping=$subtotal-$discountTotal>=250?0:9.90;$discountFactor=$subtotal>0?1-($discountTotal/$subtotal):1;$tax=round($lines->sum(fn($l)=>($l['unit_price']*$l['quantity']*$discountFactor)*($l['product']->tax_rate??23)/(100+($l['product']->tax_rate??23)))+($shipping*23/123),2);$address=collect($d)->only(['name','phone','tax_number','line1','line2','postal_code','city','region','country_code'])->all();$billing=!empty($d['billing_line1'])?['name'=>$d['billing_name'],'tax_number'=>$d['tax_number']??null,'line1'=>$d['billing_line1'],'line2'=>$d['billing_line2']??null,'postal_code'=>$d['billing_postal_code'],'city'=>$d['billing_city'],'region'=>$d['billing_region']??null,'country_code'=>'PT']:$address;
  $order=DB::transaction(function()use($r,$lines,$d,$subtotal,$discount,$discountTotal,$shipping,$tax,$address,$billing){$order=Order::create(['public_id'=>(string)Str::uuid(),'number'=>'TRP-'.now()->format('ymd').'-'.strtoupper(Str::random(6)),'user_id'=>$r->user()->id,'discount_code_id'=>$discount?->id,'subtotal'=>$subtotal,'discount_total'=>$discountTotal,'shipping_total'=>$shipping,'tax_total'=>$tax,'total'=>$subtotal-$discountTotal+$shipping,'email'=>$d['email'],'phone'=>$d['phone'],'customer_name'=>$d['name'],'tax_number'=>$d['tax_number']??null,'shipping_address'=>$address,'billing_address'=>$billing,'customer_notes'=>$d['notes']??null]);foreach($lines as $l)$order->items()->create(['product_id'=>$l['product']->id,'product_variant_id'=>$l['variant']?->id,'sku'=>$l['variant']?->sku??$l['product']->reference,'name'=>$l['product']->name,'variant_name'=>$l['variant']?->name,'quantity'=>$l['quantity'],'unit_price'=>$l['unit_price'],'tax_rate'=>$l['product']->tax_rate??23,'line_total'=>round($l['unit_price']*$l['quantity'],2),'snapshot'=>['options'=>$l['variant']?->options]]);return $order;});
  try{$session=$stripe->create($order);}catch(\Throwable $e){report($e);$order->update(['status'=>'payment_failed']);return back()->withErrors(['payment'=>'Não foi possível iniciar o pagamento. Tente novamente ou contacte-nos.']);}return redirect()->away($session->url);
 }
 public function success(Request $r,StripeCheckoutService $stripe){$id=$r->query('session_id');if($id)try{$stripe->fulfill($id);}catch(\Throwable $e){report($e);} $order=Order::where('stripe_checkout_session_id',$id)->first();if($order&&$order->user_id===$r->user()->id)$r->session()->forget('order_cart');return view('checkout-success',compact('order'));}
 public function cancel(Request $r,Order $order){abort_unless($order->user_id===$r->user()->id,404);return view('checkout-cancel',compact('order'));}
 public function requestConfirmation(Request $r,CartController $cart){$lines=$cart->hydrate($r);abort_if($lines->isEmpty(),422);$d=$r->validate(['name'=>'required|string|max:120','email'=>'required|email|max:160','phone'=>'required|string|max:40','tax_number'=>'nullable|string|max:32','line1'=>'required|string|max:180','line2'=>'nullable|string|max:180','postal_code'=>'required|string|max:20','city'=>'required|string|max:100','region'=>'required|string|max:100','country_code'=>'required|in:PT','notes'=>'nullable|string|max:2000','terms'=>'accepted']);$address=collect($d)->only(['name','phone','line1','line2','postal_code','city','region','country_code'])->all();$subtotal=$lines->every(fn($line)=>$line['unit_price']!==null)?round($lines->sum(fn($line)=>$line['unit_price']*$line['quantity']),2):null;$order=DB::transaction(function()use($r,$d,$address,$subtotal,$lines){$order=OrderRequest::create(['user_id'=>$r->user()->id,'reference'=>'TRP-'.now()->format('ymd').'-'.strtoupper(Str::random(5)),'customer_type'=>$r->user()->customer_type??'private','name'=>$d['name'],'email'=>$d['email'],'phone'=>$d['phone'],'company'=>$r->user()->company,'tax_number'=>$d['tax_number']??null,'region'=>$d['region'],'shipping_address'=>$address,'subtotal'=>$subtotal,'currency'=>'EUR','fulfilment_type'=>'delivery','notes'=>$d['notes']??null,'status'=>'new']);foreach($lines as $line)$order->items()->create(['product_id'=>$line['product']->id,'product_variant_id'=>$line['variant']?->id,'product_name'=>$line['product']->name,'variant_name'=>$line['variant']?->name,'quantity'=>$line['quantity'],'notes'=>$line['notes']]);return $order->load('items');});try{Mail::to($order->email)->send(new OrderRequestConfirmation($order,false));$to=SiteSetting::where('key','email')->value('value')?:config('mail.from.address');Mail::to($to)->send(new OrderRequestConfirmation($order,true));$order->update(['notified_at'=>now()]);}catch(\Throwable $e){report($e);}$r->session()->forget('order_cart');return redirect()->route('order-request.success',$order->reference);}
 public function requestSuccess(string $reference){return view('order-success',['order'=>OrderRequest::where('reference',$reference)->firstOrFail()]);}
}
